### ISSUE TITLE
keymirror module not found error

### ISSUE THREAD

**Issue by GulberaTekin** [GulberaTekin/react#5104]
Original issue: https://github.com/facebook/react/issues/5201

Hi,
I'm using the tutorial https://scotch.io/tutorials/creating-a-simple-shopping-cart-with-react-js-and-flux.
It works in 0.13 version but in 0.14 version require('react/lib/keyMirror') no longer works. I updated the code to use require('keymirror') as in the todo example but this also is returning "Cannot find module 'keymirror'"
